### PR TITLE
Templates references

### PR DESCRIPTION
**Pull request by hansvancalster**
Adds bibliography / csl fields and (empty) references.yaml files to templates

### CODE REVIEW

**Review by ElsLommelen — APPROVED** [review]
The changes seem fine to me (but you may want to ask @florisvdh as well to have a look at it next week, as he seems to have a better knowledge and more experience on it).  What I wonder: do I check if a file `references.yaml` or `referenties.yaml` is present, or do we allow other formats or other names as well?

Also: I notice an error which is not related to your changes.  If you don't solve it now, do you want me to solve it in the v0.2.4 pull request?  It is not a big deal, only a matter of readable code, and I strongly suggest changing it because it would make debugging much easier.

**Comment by hansvancalster** [comment]
> The changes seem fine to me (but you may want to ask @florisvdh as well to have a look at it next week, as he seems to have a better knowledge and more experience on it). 

Will do.

>What I wonder: do I check if a file `references.yaml` or `referenties.yaml` is present, or do we allow other formats or other names as well?

It wont hurt to allow other formats and names as well. A bibliography field can have more than one bibliography file.

 
> Also: I notice an error which is not related to your changes. If you don't solve it now, do you want me to solve it in the v0.2.4 pull request? It is not a big deal, only a matter of readable code, and I strongly suggest changing it because it would make debugging much easier.

Yes thank you. Could it be that is error is already solved in your check-structure branch?

**Comment by ElsLommelen** [comment]
> Yes thank you. Could it be that is error is already solved in your check-structure branch?

No, I didn't make any changes in these files, I don't know why this error suddenly pops up now (i.e. it is surprising why it wasn't detected in my check-structure branch).

**Review by florisvdh — APPROVED** [review]
Nice addition!

Should the compilation of a template with this change be tested? (I've never compiled an Rmd file referring an empty bibliography file, but it should not pose a problem!)

**Comment by hansvancalster** [comment]
I tried it, the emty references.yaml file is not a problem.

**Pull request merged**
