### PR TITLE
V0.3.1

### PR DESCRIPTION
**Pull request by hansvancalster**
Patches to address remaining issues

### CODE REVIEW

**Comment by hansvancalster** [comment]
Fixes issue #79

**Comment by ElsLommelen** [comment]
I tested this PR with regard to issue #79, but unfortunately it doesn't work completely as expected.  It indeed only commits the change in `index.Rmd` (which is better than before), but unfortunately, unrelated changes that I make in my workspace before running the function, seem to be undone.  This unexpected behaviour is very annoying, firstly because one doesn't expect a function affecting unrelated changes (so while debugging this is likely to be overlooked), and secondly because one doesn't want to redo all changes after running the function.  Isn't it possible to just stage and commit the changes that function `update_version_number()` made in `index.Rmd` without affecting (unstaged) changes in other files?  Why not just using `git_add("index.Rmd", repo = path)` to add this commit?  The risk that someone accidentally has uncommitted changes in `index.Rmd` when running `update_version_number()` seems very small (and you may add a warning to cover this).  On the other hand, losing uncommitted changes (to other files) unexpectedly, can be very annoying.

(The change I made before running the function, was removing an entire file.  I'm not sure if other changes such as edited files or additions will be affected in the same way.)

**Comment by hansvancalster** [comment]
> , unrelated changes that I make in my workspace before running the function, seem to be undone. 

Can you check if [ec26713](https://github.com/inbo/protocolhelper/pull/80/commits/ec267132ee271cb10e59cfa630a73cf4a603bf8f) fixes the issue. As discussed, the problem is likely due to `get_version_number()` in which the main branch needs to be checked out and which might result in loss of uncommitted changes in non-interactive mode.

**Comment by ElsLommelen** [comment]
Yes, this fixes the problem!  Great!
At least in an non interactive session (and as far as needed for my case of automation), because in an interactive session one encounters the error that the working directory should be clean.  Due to the nature of the function (just getting a version number), a clean wd is an inappropriate requirement in my opinion, so you may want to reconsider this (now there is a good solution).  At least if it is safe enough to be used with `update_version_number()` (i.e. you may want to drop a similar error in this function in case the working directory contains uncommitted changes in `index.Rmd`, or overall, as you don't want to take the risk that a user gets into troubles there).  As mentioned, this is not needed for the GHA, it is just a matter of making your function more user friendly in cade they want to use it locally.  So I leave it up to you to decide.

**Review by ElsLommelen — APPROVED** [review]
Ah, don't forget to describe the changes in `NEWS.md`.

**Comment by hansvancalster** [comment]
> Due to the nature of the function (just getting a version number), a clean wd is an inappropriate requirement in my opinion,

I think it is safer to keep `checklist::clean_dir` as a first step in `get_version_number` in an interactive session. It makes sure the branches are aligned with main branch and all local branches (including main) are up to date with remote counterparts. Without this step, the local main branch could be behind the remote counterpart and there is a risk that `get_version_number` would return a version number that is already in use.

**Comment by ElsLommelen** [comment]
You're right, I didn't think of that.
In this case you may want to add this in the documentation of the function.  As a user, I wouldn't think of cleaning my working directory before asking for a version number, so the error would come as a surprise.  Even if I wouldn't have read the documentation beforehand, reading there that a clean and up-to-date local version is important to get the right version number, would make this error much more acceptable (or I would at least understand why this is important).

**Comment by hansvancalster** [comment]
Thank you for reviewing @ElsLommelen !

**Pull request merged**
