### PR TITLE
V0.3.2

### PR DESCRIPTION
**Pull request by hansvancalster**

### CODE REVIEW

**Comment by hansvancalster** [comment]
@ThierryO can you have a look at the failing checks? I updated checklist package and ran `checklist::setup_package()` in the hope this would fix the failing checks, but maybe something else is going wrong?

**Comment by ElsLommelen** [comment]
@hansvancalster If you want to have it published on Zenodo, don't forget to add a second keyword (additional to `R package` that is automatically added if you add another one).
Also: I don't see any recent changes that could explain the fail on the windows check now (while it was passing some hours ago), so you may want to rerun this check.  Maybe gert or the pathway to the installation of gert was unavailable for a short time while running the test?
The ubuntu check already failed yesterday, maybe this has to do with the fact that the checks of package checklist failed on the main?

**Comment by ThierryO** [comment]
Have a look at the raw logs. The package `gert` failed to install on Windows. On Ubuntu the problem is due to one of the dependencies of pkgdown.

**Comment by ElsLommelen** [comment]
@hansvancalster For the ubuntu, try adding `sudo apt-get install -y libharfbuzz-dev libfribidi-dev` at the system dependencies (or add the two packages behind the installation of libcurl)

**Comment by hansvancalster** [comment]
> Have a look at the raw logs. The package `gert` failed to install on Windows. On Ubuntu the problem is due to one of the dependencies of pkgdown.

Based on https://github.com/r-lib/usethis/issues/1410, I think the `gert` package failing to install issue will be gone when CRAN has updated Windows binaries for version 1.8.0.

**Comment by hansvancalster** [comment]
> @hansvancalster For the ubuntu, try adding `sudo apt-get install -y libharfbuzz-dev libfribidi-dev` at the system dependencies (or add the two packages behind the installation of libcurl)

Thanks @ElsLommelen, that worked. @ThierryO should [82ffc5e](https://github.com/inbo/protocolhelper/pull/81/commits/82ffc5e9167db58d00b188bfacf096a607c5888a) be added to `checklist` too?

**Comment by ThierryO** [comment]
> > @hansvancalster For the ubuntu, try adding `sudo apt-get install -y libharfbuzz-dev libfribidi-dev` at the system dependencies (or add the two packages behind the installation of libcurl)
> 
> Thanks @ElsLommelen, that worked. @ThierryO should [82ffc5e](https://github.com/inbo/protocolhelper/pull/81/commits/82ffc5e9167db58d00b188bfacf096a607c5888a) be added to `checklist` too?

This is already installed in the `checklist` [Docker](https://github.com/inbo/checklist/blob/84cd5114dbc8125c6c99721716fca16e5a92375a/Dockerfile#L32)

**Comment by ThierryO** [comment]
The problem occurs in a GHA that is provided by `checklist` but doesn't rely on `checklist`. In this special case, `checklist` is loaded because it is a dependency of `protocolhelper`.

**Pull request merged**
