### PR TITLE
Create spp

### PR DESCRIPTION
**Pull request by hansvancalster**
This PR addresses #31.

To try it, you can use the R code in the forked protocols repo https://github.com/hansvancalster/protocols/blob/master/src/management/setup_dummies.R

### CODE REVIEW

**Review by florisvdh — COMMENTED** [review]
Thanks for the work @hansvancalster ! Some suggestions:

#### With regard to the `create_sfp()` vs. `create_spp()` functions

Most code and documentation is identical between `create_sfp()` and `create_spp()`, which makes it harder to maintain / compare and causes more overhead. (Note: comparison is available in 6a2dd23 - but branch `create_spp_compare` is to be deleted afterwards.) I suggest therefore:
- to merge current code of both functions into one function `create_protocol()`, with an extra `protocol_type` argument (leading to some if-else constructs here and there) and which exposes both the `theme` and `project_name` arguments
- to also export (hence, keep) the `create_sfp()` and `create_spp()` functions, under the same documentation (not repeating documentation), and these would have their current arguments and defaults. (An approach with `roxygen2` syntax is described [here](https://roxygen2.r-lib.org/articles/rd.html#documenting-multiple-functions-in-the-same-file) although in [this](https://github.com/r-spatial/sf/blob/44b1f90cda6eecef658d91fab2d14864a53e46ef/R/sfg.R#L71) `sf` example it is approached somewhat different). The functions would be assigned (below for create_spp example) as follows:
  
  ```r
  create_spp <- function(title, subtitle, date = Sys.Date(), <and so on>) {
     create_protocol(protocol_type = "spp", 
              title = title, 
              subtitle = subtitle,  
              date = date, <and so on>)
  }
  ```

- the documentation title / description then needs to be a bit widened to encompass the three functions.
- an option, if you don't want to export `create_protocol()`, is to make the latter internal (marked as internal with `#' @keywords internal` and by not adding `#' @export` above it)

#### With regard to the templates

- the same additions as in PR #34 (--> still to be merged) will be needed in the templates
- the template markdown comments are still referring to 'veldprotocol'.
- the template should accommodate appendices that are other protocols, which in that case are effectively subprotocols (see emaildiscussion ca. 24 Sep 2020). In that setup it is questionable to entirely copy over the _sfp_ chapter structure in the project protocol itself, as we don't want to invoke repetition. IMO the spp master protocol could be kept much shorter than its subprotocols. The project protocol for the soil compartment in MNE could e.g. have following chapters (I dropped some that rather seem more relevant for the - more extensive - subprotocols):
  1. Wijzigingen t.o.v. vorige versies
  2. Afhankelijkheden
  2. Onderwerp
  3. Extra benodigdheden t.o.v. de subprotocols
  3. Overkoepelende werkwijze met verwijzing naar subprotocols
      - this would be an overview of the steps encompassed by the project protocol, with criteria or some guiding _key_ when to do what. E.g.:
        1.  Go to a site as indicated in document X with the measurement plan for the monitoring
        2. - If the site has not yet been registered as a unit, follow subprotocol A (unit-selection protocol - which is common to many project protocols).
           - If it has been defined in the field, <take the necessary steps to reconfirm the unit's status (population membership etc.) - that may also be part of subprotocol A>.
        3. Follow subprotocol B to (re)define points for subsampling in soil monitoring.
        4. Follow subprotocol C to do the laboratory measurements in soil monitoring.
      - the above is rather simplified (e.g. in d multiple subprotocols may be needed, and in practice extra steps and conditions would need to be added). So more aspects may need to be considered, but I think it demonstrates the idea already. The aim is to assemble the subprotocols in a coherent master protocol which fills remaining gaps which are not in specific subprotocols, such as when to apply a specific subprotocol or not (criteria) or the addition of smaller extra steps which don't deserve their own subprotocol.
  3. Extra aspecten van kwaliteitszorg t.o.v. de subprotocols (--> no repetition)
  3. Extra aspecten van veiligheid t.o.v. de subprotocols (--> no repetition)
  - Bijlage A: subprotocol ....
  - Bijlage B: subprotocol ....
  - Bijlage C: subprotocol ....
  Importantly, the subprotocols in the appendices should be inserted programmatically, preferably triggered by their versions as defined in chapter 2 (dependencies). They would typically be existing (or yet to be made) sfp, sap, sip or sop protocols, in some cases (especially for **sfp**) that would need to be a project-specific **variant** by using a projectvariant-parameter (is that accommodated already?). So in that case chapter 2 of the _project_ protocol would need to define both the version and the project-specific variant in order to insert a correct subprotocol.

**Comment by hansvancalster** [comment]
@ThierryO I noticed - after building protocolhelper package from this branch and running the tests with [this script](https://github.com/hansvancalster/protocols/blob/master/src/management/setup_dummies.R) - the English version of the protocol is not published by `protocolhelper:::render_release()`. Can you have a look?

**Comment by ThierryO** [comment]
Note that every protocol needs a unique version number. In your example two protocols have the same version number

_Originally posted by @ThierryO in https://github.com/inbo/protocolhelper/issues/36#issuecomment-762373814_

**Comment by hansvancalster** [comment]
> Note that every protocol needs a unique version number. In your example two protocols have the same version number
> 
> _Originally posted by @ThierryO in [#36 (comment)](https://github.com/inbo/protocolhelper/pull/36#issuecomment-762373814)_

See https://github.com/inbo/protocols/blob/master/CONTRIBUTING.md#translations-of-protocols. In the contributing guide we stated that different language versions of the same protocol should have the same protocol version number. If we follow that logic, `protocolhelper:::render_release()` should be changed accordingly. I think it makes sense.

**Comment by ThierryO** [comment]
IMHO we should use different version numbers. Things can get lost in translation. A different version number for a version in a different language makes more sense to me.

**Comment by hansvancalster** [comment]
On the plus side, that would make management of the protocols repo easier. The downside is that it becomes harder to know which Dutch protocol corresponds with which English protocol (apart from linguistic freedom). I can imagine that for international projects, different language versions should really be the same in terms of contents (compare it to translations of European legislation) and it should be easy look them up. @florisvdh your thoughts on this?

**Comment by ThierryO** [comment]
If a protocol is a pure translation of another protocol, then you could reference that protocol version as the source version. This will allow divergence of protocols. e.g. the first English version is a translation of a Dutch version and mentions that version as source. The second English version diverges from the Dutch version and no longer mentions a source.

**Comment by florisvdh** [comment]
I think the suggestion of @ThierryO provides more flexibility when updating protocols. It seems like a good idea to add an extra chapter in the templates for saying from which protocol code (with language) and version number this version has been translated.

But should the suggestion not essentially refer to unique _protocol codes_ (between translations), not necessarily version numbers? I.e. insert the language code into the protocol code; different translations still use the same _protocol number_ (don't confuse with version number). Example: `sfp-401-en` and `sfp-401-nl`.

- Although we generally recommend working on 1 protocol in one branch (hence leading to unique PR, release and version number), there shouldn't be a conceptual problem when updating a few related ones at the same time, hence receiving the same version number on release (leading to one common generic tag, but different protocol codes, hence also multiple different specific tags referring to the same commit).

Relevant sections for reference:

- [Release model](https://github.com/inbo/protocols#release-model)
- [Protocol code and protocol number](https://github.com/inbo/protocols#protocol-code-and-protocol-number-)
- [Folder & filename syntaxis](https://github.com/inbo/protocols#folder-and-filename-syntaxis)
- [Translation of protocols](https://github.com/inbo/protocols/blob/master/CONTRIBUTING.md#translations-of-protocols)

Because in the currently recommended approach (= in the documentation) we keep protocol codes _and_ protocol versions equal between different translations, we also recommend (in the last referred section):

> All language versions of the same protocol-version should be updated in the same Pull Request

> In case one of the languages of a multi-language protocol is discontinued for some reason, the Rmarkdown files for the discontinued language should be deleted in the protocols repo

These could already be relaxed if the **protocol code** (which is also part of the specific tag) would be like `sfp-401-en` - hence essentially considering translations as different protocols while still connecting them with the protocol number. If this is followed, then the name syntaxis of folders and compiled files (defined in _bookdown.yml) would become `<protocol-code>_<short-title>`~`_<language-code>`~ (where language code is already part of the protocol code).

Putting language code inside the protocol code still leaves two options open: either insist on 1 version number = 1 released protocol, or not.

**Comment by hansvancalster** [comment]
> I think the suggestion of @ThierryO provides more flexibility when updating protocols. It seems like a good idea to add an extra chapter in the templates for saying from which protocol code (with language) and version number this version has been translated.

I agree. However, I would not add another chapter but use NEWS.Rmd for this purpose.

>These could already be relaxed if the protocol code (which is also part of the specific tag) would be like sfp-401-en - hence essentially considering translations as different protocols while still connecting them with the protocol number. If this is followed, then the name syntaxis of folders and compiled files (defined in _bookdown.yml) would become <protocol-code>_<short-title>_<language-code> (where language code is already part of the protocol code).

Good idea

> Putting language code inside the protocol code still leaves two options open: either insist on 1 version number = 1 released protocol, or not.

I think insisting 1 version number = 1 released protocol is cleanest.

If you both agree, I can start making changes:

- [ ] update https://github.com/inbo/protocols#folder-and-filename-syntaxis
- [ ] update https://github.com/inbo/protocols#protocol-code-and-protocol-number-
- [ ] update https://github.com/inbo/protocols/blob/master/CONTRIBUTING.md#translations-of-protocols
- [ ] update https://github.com/inbo/protocols/blob/master/src/management/protocols-gitflow-model.png
- [ ] update `protocolhelper::create_protocol()`

**Comment by hansvancalster** [comment]
> With regard to the `create_sfp()` vs. `create_spp()` functions ...

Done in 662b881

> With regard to the templates ...

See 5f7b954. I suggest we create a new function `protocolhelper::add_subprotocol` which can be used in a chunk in the Appendices chapters to programmatically add a subprotocol.

Ideas for this function were already discussed in #14. In addition, we should be able to pass parameter values for parameterized markdown.

**Comment by florisvdh** [comment]
Thanks for the updates @hansvancalster.

> I would not add another chapter but use NEWS.Rmd for this purpose.

- Agree - NEWS.Rmd is the first chapter IIUC.

> I think insisting 1 version number = 1 released protocol is cleanest.

- @ThierryO is it effectively required in the (rendering) workflow, or is it just a recommendation? (cf. the branching model)

>  I suggest we create a new function `protocolhelper::add_subprotocol` which can be used in a chunk in the Appendices chapters to programmatically add a subprotocol.

- An alternative could be to auto-generate a URL instead, that links to the correct version of the subprotocol. But it's not clear to me how project-dependent YAML parameters would work out. I assume the rendered versions (for subprotocols) will only take the default value for their project-dependent YAML parameters? In that case, the project-customized version will need to be rendered inside the project protocol with `protocolhelper::add_subprotocol` as you suggest.

**Comment by hansvancalster** [comment]
> * An alternative could be to auto-generate a URL instead, that links to the correct version of the subprotocol. But it's not clear to me how project-dependent YAML parameters would work out. I assume the rendered versions (for subprotocols) will only take the default value for their project-dependent YAML parameters? In that case, the project-customized version will need to be rendered inside the project protocol with `protocolhelper::add_subprotocol` as you suggest.

Yes, for [parameterized reports](https://bookdown.org/yihui/rmarkdown/parameterized-reports.html) with non-default param values, we would have to render the protocol again and this should be handled by `protocolhelper::add_subprotocol`. Autogenerate URL is not an option in this case.

**Comment by ThierryO** [comment]
> * @ThierryO is it effectively required in the (rendering) workflow, or is it just a recommendation? (cf. the branching model)

The current render workflow assumes that each version number refers to a single protocol code in only one language. A nice bonus is that the version number becomes a unique identifier. So you can use it to double check the protocol code and language. Maybe we should generate and publish such a table in a machine readable format.

**Review by florisvdh — APPROVED** [review]
@hansvancalster It seems that you re-tested and it worked. Well done!

**Comment by florisvdh** [comment]
@hansvancalster I suggest to delete the `create-spp` branch on the remote (see button above) and update the repo settings to do this automatically. That avoids lingering branches that were merged already.

In settings, you find this under 'options' as (copied from another repo):

> afbeelding

**Pull request merged**
